config/routes.rb
Hwk2::Application.routes.draw do

  resources :uploads

  resources :assignments

  resources :lectures

  resources :courses do
    resources :users
    get 'addUsers' => 'courses#addUsersForm', :as => 'addUsers'
    post 'addUsers' => 'courses#addUsers', :as => 'addUsers'
   end

  resources :users
  
  
  resources :sessions
  
  root :to => 'sessions#new'
  match 'signup' => 'users#new', :as => 'signup' 
  get 'login' => 'sessions#new', :as => 'login'
  post 'login' => 'sessions#create', :as => 'login'
  match 'logout' => 'sessions#destroy', :as => 'logout'

  

end

app/models/upload.rb
class Upload
  include Mongoid::Document

  belongs_to :course

  field :title, type: String
  field :date_time, type: String
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(params[:upload])

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render json: @upload, status: :created, location: @upload }
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date_time %><br />
    <%= f.text_field :date_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Date time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uploads.each do |upload| %>
  <tr>
    <td><%= upload.title %></td>
    <td><%= upload.date_time %></td>
    <td><%= link_to 'Show', upload %></td>
    <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
    <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @upload.title %>
</p>

<p>
  <b>Date time:</b>
  <%= @upload.date_time %>
</p>


<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>